name = "validade-zero-api-local"
main = "src/index.ts"
compatibility_date = "2026-06-19"
workers_dev = true

[vars]
VALIDADE_ZERO_APP_ENV = "local"
SAFE_PROBE_DEFAULT_VALUE = "sonda-segura-ficticia"

[triggers]
crons = ["*/15 * * * *"]
